
export const products = [
    {
        id: 1,
        title: "Real Madrid Negra",
        price: 15000,
        stock: 5,
        description: "Camisa Original Real Madrid, Alternativa. ",
        category: "Futbol",
        img: "https://res.cloudinary.com/dybsirwia/image/upload/v1679158815/E-commerce/Camisas%20Futbol/RealMadridNegra_im2etd.jpg",
    },
    {
        id: 2,
        title: "ManchesterCity",
        price: 14500,
        stock: 5,
        description: "Camisa Original Manchester City, Tradicional.",
        category: "Futbol",
        img: "https://res.cloudinary.com/dybsirwia/image/upload/v1679158812/E-commerce/Camisas%20Futbol/ManchesterCity_hadb09.jpg",
    },
    {
        id: 3,
        title: "New York Yankees",
        price: 19000,
        stock: 5,
        description: "Camisa Original New York Yankees, Tradicional.",
        category: "Beisbol",
        img: "https://res.cloudinary.com/dybsirwia/image/upload/v1679158869/E-commerce/Camisas%20Beisbol/Yankees_vg3h8i.jpg",
    },
    {
        id: 4,
        title: "New York Mets",
        price: 17800,
        stock: 5,
        description: "Camisa Original New York Mets, Tradicional.",
        category: "Beisbol",
        img: "https://res.cloudinary.com/dybsirwia/image/upload/v1679158869/E-commerce/Camisas%20Beisbol/Mets_ge8fjo.jpg",
    },
    {
        id: 5,
        title: "Selección Argentina",
        price: 17800,
        stock: 5,
        description: "Camisa Original Seleccion Argentina de BasketBall",
        category: "Basket",
        img: "https://res.cloudinary.com/dybsirwia/image/upload/v1679158932/E-commerce/Camisas%20Basket/ArgentinaBasket_htj8tl.jpg",
    },
    {
        id: 6,
        title: "Sixers",
        price: 17800,
        stock: 5,
        description: "Camisa Original de los Sixers, tradicional",
        category: "Basket",
        img: "https://res.cloudinary.com/dybsirwia/image/upload/v1679158929/E-commerce/Camisas%20Basket/Sixers_qxu4s0.jpg",
    },
];